# Generated by Django 4.0.4 on 2022-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_player_players_delete_allplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Last_5_games_points',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
